name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 機能'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 バグ修正'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 メンテナンス'
    labels:
      - 'chore'
      - 'maintenance'
  - title: '📚 ドキュメント'
    labels:
      - 'documentation'
  - title: '⬆️ 依存関係'
    labels:
      - 'dependencies'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'maintenance'
      - 'dependencies'
  default: patch

template: |
  ## 変更点 🚀

  $CHANGES

  ## インストール方法 📦

  ### Gradle
  ```groovy
  dependencies {
      implementation 'io.github.shizuya-aishima:csvxlator-core:$RESOLVED_VERSION'
  }
  ```

  ### Maven
  ```xml
  <dependency>
      <groupId>io.github.shizuya-aishima</groupId>
      <artifactId>csvxlator-core</artifactId>
      <version>$RESOLVED_VERSION</version>
  </dependency>
  ```

  ## 👩‍💻 コントリビューター

  $CONTRIBUTORS 